services:
  db:
    image: postgres:17-alpine
    volumes:
      - ./.db:/var/lib/postgresql/data/
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}

  service:
    build: .
    restart: on-failure
    volumes:
      - .:/service
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file: ".env"
    depends_on:
      - db
